



#define POWER_ON_STATE 			1
#define POWER_OFF_STATE 		0
#define MODE_SWITCH_STATE 	3
#define DEVICE_RUN   				4
#define DEVICE_NORMAL 			5

// (s)
#define POWER_ON_OFF_TOGGLE_TIME_SEC 	3
#define MODE_CHANGE_BUTTON_TIME_SEC 	1
#define RUN_MODE_FUNCTION_TIME_SEC		1

#define FPS_DEVICE_BY_CLOCK 650000					// Hz
#define FRAME_POWER_BUTTON_TOGGLE 	(POWER_ON_OFF_TOGGLE_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define FRAME_MODE_BUTTON_SWITCH 		(RUN_MODE_FUNCTION_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define FRAME_RUN_MODE_FUNC 				(RUN_MODE_FUNCTION_TIME_SEC * FPS_DEVICE_BY_CLOCK)

// (V)
#define BATTERY_CHECK_STATE_1   2.8
#define BATTERY_CHECK_STATE_2   3
#define BATTERY_CHECK_STATE_3   3.3
#define BATTERY_CHECK_STATE_4   3.7

#define MODE_1  1
#define MODE_2  2
#define MODE_3  3


// (s)
#define MODE_1_TIME_SEC  1
#define MODE_2_TIME_SEC  5
#define MODE_3_TIME_SEC  10

#define MODE_1_FRAME 		(MODE_1_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define MODE_2_FRAME 		(MODE_2_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define MODE_3_FRAME 		(MODE_3_TIME_SEC * FPS_DEVICE_BY_CLOCK)

