

// DEVICE CURRENT STATE
#define POWER_OFF_STATE 		0
#define POWER_ON_STATE 			1
#define MODE_SWITCH_STATE 	2


// DEVICE RUNNING TIME EACH FUNCTION
// [s]
#define POWER_ON_OFF_TOGGLE_TIME_SEC 	3
#define MODE_CHANGE_BUTTON_TIME_SEC 	1
#define CHECK_BATTERY_PERIOD_MIN			10

#define RUN_MODE_FUNCTION_TIME_SEC		1
#define RUN_AOI_TIME_SEC							1

// [Hz]
#define FPS_DEVICE_BY_CLOCK 					800000					
#define FPS_MODE_CLOCK 								175000


// [Frame]
#define FRAME_POWER_BUTTON_TOGGLE 		(POWER_ON_OFF_TOGGLE_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define FRAME_MODE_BUTTON_SWITCH 			(MODE_CHANGE_BUTTON_TIME_SEC * FPS_DEVICE_BY_CLOCK)

#define FRAME_CHECK_BATTERY_PERIOD		(CHECK_BATTERY_PERIOD_MIN * FPS_MODE_CLOCK * 60)
#define FRAME_RUN_MODE_FUNC 					(RUN_MODE_FUNCTION_TIME_SEC * FPS_MODE_CLOCK)
#define FRAME_RUN_AOI_FUNC 						(RUN_AOI_TIME_SEC * FPS_MODE_CLOCK)


// BATTERY CHECK Configuration
// [V]
#define BATTERY_CHECK_STATE_1   2.8
#define BATTERY_CHECK_STATE_2   3
#define BATTERY_CHECK_STATE_3   3.3
#define BATTERY_CHECK_STATE_4   3.7

#define BATTERY_CHECK_STATE_1_ADC_MIN   0
#define BATTERY_CHECK_STATE_1_ADC_MAX   3200

#define BATTERY_CHECK_STATE_2_ADC_MIN   3200
#define BATTERY_CHECK_STATE_2_ADC_MAX   3400

#define BATTERY_CHECK_STATE_3_ADC_MIN   3400
#define BATTERY_CHECK_STATE_3_ADC_MAX   3800

#define BATTERY_CHECK_STATE_4_ADC_MIN   3800
#define BATTERY_CHECK_STATE_4_ADC_MAX   4096



// MODE Configuration
#define MODE_1  1
#define MODE_2  2
#define MODE_3  3


// [s]
#define MODE_1_TIME_SEC  2
#define MODE_2_TIME_SEC  3
#define MODE_3_TIME_SEC  5

// [Frame]
#define MODE_1_FRAME 						(MODE_1_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_2_FRAME 						(MODE_2_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_3_FRAME 						(MODE_3_TIME_SEC * FPS_MODE_CLOCK)

