

// DEVICE CURRENT STATE
#define POWER_OFF_STATE 		0
#define POWER_ON_STATE 			1
#define MODE_SWITCH_STATE 	2

// DEVICE CLOCKS [Hz]
#define FPS_DEVICE_BY_CLOCK 					400000					
#define FPS_MODE_CLOCK 								175000

// MODE STATE CONFIGURATION
#define MODE_0  0
#define MODE_1  1
#define MODE_2  2
#define MODE_3  3
#define MODE_4  4
#define MODE_5  5
#define MODE_6  6
#define MODE_7  7
#define MODE_8  8
#define MODE_9  9




/*
---------------------USER SETTING----------------------
*/
// MODE RUNNING TIME EACH STATE[s]
#define MODE_0_TIME_SEC  0.1
#define MODE_1_TIME_SEC  0.3
#define MODE_2_TIME_SEC  0.5
#define MODE_3_TIME_SEC  0.7
#define MODE_4_TIME_SEC  0.9
#define MODE_5_TIME_SEC  1.1
#define MODE_6_TIME_SEC  1.1
#define MODE_7_TIME_SEC  1.1
#define MODE_8_TIME_SEC  1.1
#define MODE_9_TIME_SEC  1.1



// DEVICE RUNNING TIME EACH FUNCTION[s]
#define POWER_ON_OFF_TOGGLE_TIME_SEC 	1
#define MODE_CHANGE_BUTTON_TIME_SEC 	0.5
#define RUN_MODE_FUNCTION_TIME_SEC		0.5
#define RUN_AOI_TIME_SEC							1						// 3 -> 1  // 2021.11.29


#define PIN_26_POWER_ON_SEC 					5
#define PIN_26_POWER_OFF_SEC 					2

// SOI DELAY TIME[s]
#define SOI_DELAY_TIME_SEC 1

/*
---------------------------------------------------------
*/

// Device Run Frame
#define FRAME_POWER_BUTTON_TOGGLE 		(POWER_ON_OFF_TOGGLE_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define FRAME_MODE_BUTTON_SWITCH 			(MODE_CHANGE_BUTTON_TIME_SEC * FPS_DEVICE_BY_CLOCK)
#define FRAME_RUN_MODE_FUNC 					(RUN_MODE_FUNCTION_TIME_SEC * FPS_MODE_CLOCK)
#define FRAME_RUN_AOI_FUNC 						(RUN_AOI_TIME_SEC * FPS_MODE_CLOCK)

// Mode Run Frame
#define MODE_0_FRAME 						(MODE_0_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_1_FRAME 						(MODE_1_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_2_FRAME 						(MODE_2_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_3_FRAME 						(MODE_3_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_4_FRAME 						(MODE_4_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_5_FRAME 						(MODE_5_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_6_FRAME 						(MODE_6_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_7_FRAME 						(MODE_7_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_8_FRAME 						(MODE_8_TIME_SEC * FPS_MODE_CLOCK)
#define MODE_9_FRAME 						(MODE_9_TIME_SEC * FPS_MODE_CLOCK)



#define PIN_26_POWER_ON_FRAME 					(PIN_26_POWER_ON_SEC * FPS_MODE_CLOCK)
#define PIN_26_POWER_OFF_FRAME 					(PIN_26_POWER_OFF_SEC * FPS_MODE_CLOCK)

// SOI DELAY TIME[s]
#define SOI_DELAY_TIME_FRAME 		( SOI_DELAY_TIME_SEC * FPS_MODE_CLOCK)

// 
#define CHEKING_BATTERY_TIME_SEC 				1
#define CHEKING_BATTERY_TIME_FRAME 			( CHEKING_BATTERY_TIME_SEC * FPS_DEVICE_BY_CLOCK)


// BATTERY CHECK Configuration
// [V]
#define BATTERY_CHECK_STATE_1_ADC_MIN   2988
#define BATTERY_CHECK_STATE_1_ADC_MAX   3792

#define BATTERY_CHECK_STATE_2_ADC_MIN   3792
#define BATTERY_CHECK_STATE_2_ADC_MAX   3800

#define BATTERY_CHECK_STATE_3_ADC_MIN   3800
#define BATTERY_CHECK_STATE_3_ADC_MAX   4000

#define BATTERY_CHECK_STATE_4_ADC_MIN   4000
#define BATTERY_CHECK_STATE_4_ADC_MAX   4095





